# Generated by Django 4.0.3 on 2022-03-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
    ]
